// <auto-generated />
using System;
using CA.JsonColumns.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA.JsonColumns.Migrations
{
    [DbContext(typeof(BlogsDbContext))]
    [Migration("20250622121313_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA.JsonColumns.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<string>("TagsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Author", b =>
                {
                    b.OwnsOne("CA.JsonColumns.Models.ContactDetails", "Contact", b1 =>
                        {
                            b1.Property<int>("AuthorId")
                                .HasColumnType("int");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AuthorId");

                            b1.ToTable("Authors");

                            b1.ToJson("Contact");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");

                            b1.OwnsOne("CA.JsonColumns.Models.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("ContactDetailsAuthorId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ContactDetailsAuthorId");

                                    b2.ToTable("Authors");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactDetailsAuthorId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Post", b =>
                {
                    b.HasOne("CA.JsonColumns.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CA.JsonColumns.Models.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CA.JsonColumns.Models.PostMetadata", "Metadata", b1 =>
                        {
                            b1.Property<int>("PostId")
                                .HasColumnType("int");

                            b1.Property<int>("Views")
                                .HasColumnType("int");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");

                            b1.OwnsMany("CA.JsonColumns.Models.PostUpdate", "Updates", b2 =>
                                {
                                    b2.Property<int>("PostMetadataPostId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("PostedFrom")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(45)");

                                    b2.Property<string>("UpdatedBy")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("UpdatedOn")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("PostMetadataPostId", "Id");

                                    b2.ToTable("PostUpdate");

                                    b2.WithOwner()
                                        .HasForeignKey("PostMetadataPostId");

                                    b2.OwnsMany("CA.JsonColumns.Models.Commit", "Commits", b3 =>
                                        {
                                            b3.Property<int>("PostUpdatePostMetadataPostId")
                                                .HasColumnType("int");

                                            b3.Property<int>("PostUpdateId")
                                                .HasColumnType("int");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<string>("Comment")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<DateTime>("CommittedOn")
                                                .HasColumnType("datetime2");

                                            b3.HasKey("PostUpdatePostMetadataPostId", "PostUpdateId", "Id");

                                            b3.ToTable("Commit");

                                            b3.WithOwner()
                                                .HasForeignKey("PostUpdatePostMetadataPostId", "PostUpdateId");
                                        });

                                    b2.Navigation("Commits");
                                });

                            b1.OwnsMany("CA.JsonColumns.Models.SearchTerm", "TopSearches", b2 =>
                                {
                                    b2.Property<int>("PostMetadataPostId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Count")
                                        .HasColumnType("int");

                                    b2.Property<string>("Term")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("PostMetadataPostId", "Id");

                                    b2.ToTable("SearchTerm");

                                    b2.WithOwner()
                                        .HasForeignKey("PostMetadataPostId");
                                });

                            b1.OwnsMany("CA.JsonColumns.Models.Visits", "TopGeographies", b2 =>
                                {
                                    b2.Property<int>("PostMetadataPostId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.PrimitiveCollection<string>("Browsers")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("Count")
                                        .HasColumnType("int");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("float");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("float");

                                    b2.HasKey("PostMetadataPostId", "Id");

                                    b2.ToTable("Visits");

                                    b2.WithOwner()
                                        .HasForeignKey("PostMetadataPostId");
                                });

                            b1.Navigation("TopGeographies");

                            b1.Navigation("TopSearches");

                            b1.Navigation("Updates");
                        });

                    b.Navigation("Author");

                    b.Navigation("Blog");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("CA.JsonColumns.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CA.JsonColumns.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CA.JsonColumns.Models.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
